#!/usr/bin/tcsh

#Section #1:
if ( $# == 0 ) then
  echo You must supply an object.
  exit
else if ( -e ~/_/i/i/$1 ) then
  mv ~/_/i/i/$1 .
  echo Done.
  if ( ( x$1 == xweight ) && ( -e button ) ) then
    echo A passageway opens.
    ln -s . d; ln -s . e; ln -s . ne; ln -s . se; ln -s . sw; ln -s . w
    mv .nw nw; mv u .u
  endif

#Section #1.5
else if ((( x$1 =~ x[19defnstuvw]* )&&(x$1 !~ x[dfstuw][ilhore]*[ldryt] ))||( ! -e ~/_/filenamesdir/$1 )) then
   echo I don\'t know what that is.

#Section #2:
else
   echo "You don't have that."
endif
